language: ruby
cache: bundler
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.1
  - jruby-18mode
  - jruby-19mode
  - rbx-2.1.1
  - ruby-head
  - jruby-head
  - ree
before_install:
  - gem update --system
  - gem --version
